spring:
  datasource:
    url: jdbc:h2:mem:shopping;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    ROOT: ERROR
    org.springframework: ERROR
    org.springframework.data: ERROR
    org.springframework.web: ERROR
    com.kbtg: INFO
    jdbc:
      sqlonly: OFF
      sqltiming: INFO
      audit: OFF
      resultset: OFF
      connection: ERROR
      resultsettable: ERROR