spring:
  datasource:
    url: jdbc:h2:mem:shopping;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2